apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notes-app
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "notes-app"
    tags.datadoghq.com/version: "0.4"
  name: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      annotations:
        # https://docs.datadoghq.com/tracing/trace_collection/library_injection/?tab=kubernetes#container-registries
        admission.datadoghq.com/python-lib.version: "v1.12.1"
        ad.datadoghq.com/notes-app.logs: '[{"source": "python"}]'
      labels:
        admission.datadoghq.com/enabled: "true"
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "notes-app"
        tags.datadoghq.com/version: "0.4"
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: min499/notes:0.4
        imagePullPolicy: Always
        command: ["/bin/bash"]
        args: ["-c", "python -m notes_app.app & /home/notes_app/generate-traffic.sh"]
        env:
        - name: DD_SERVICE_MAPPING
          value: "sqlite:notes-app-sqlite"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: PIP_NO_INDEX
          value: "1"
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 128Mi
            cpu: "0.3"
          requests:
            memory: 64Mi
            cpu: "0.1"
